# Generated by Django 5.2.3 on 2025-06-26 09:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "star",
                    models.IntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 star"),
                            (3, "3 star"),
                            (4, "4 star"),
                            (5, "5 star"),
                        ]
                    ),
                ),
                ("description", ckeditor.fields.RichTextField()),
                ("created_at", models.TimeField(auto_now_add=True)),
                ("updated_at", models.TimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("image_main", models.ImageField(upload_to="blog/image/")),
                ("image_one", models.ImageField(upload_to="blog/image/")),
                ("image_two", models.ImageField(upload_to="blog/image/")),
            ],
        ),
    ]
