# Generated by Django 5.2.3 on 2025-06-26 09:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_alter_blog_image_one_alter_blog_image_two"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="image_one",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="image_two",
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
